all:
	pdflatex presentation.tex
	bibtex presentation.aux
	pdflatex presentation.tex
	pdflatex presentation.tex

clean:
	rm *.aux
	rm *.log
	rm *.toc
	rm *.bbl
	rm *.blg
	rm *.nav
	rm *.out
	rm *.snm
	rm *.vrb 
